@startuml
'https://plantuml.com/class-diagram
'- Indicates private
'+ Indicates public
'# Indicates protected

package client {
    class Snake {}

    package model {
        class Player {}

        class InputMessageHandler {}

        class SocketClient {}
    }

    package resources {
        class arenaView {}

        class frameGameInfo {}

        class gameSelectionView {}

        class highscoreView {}

        class loginView {}

        class registryView {}

        class scoreView {}
    }

    package controller {

        class ArenaController {
        +void onExitMenuClick(ActionEvent event)
        +void onGameInfoMenuClick(ActionEvent event)
        +void centerWindowOnScreen(Stage stage)
        }

        class CenterWindowScreen {}

        class DatabaseController {}

        class gameSelectionController {}

        class HighscoreController {}

        class LoginController {
        +void initialize(URL location, ResourceBundle resources)
        #void onPlayButtonClick(ActionEvent event)
        -void run()
        -void drawBackground(GraphicsContext graphicsContext)
        -void onExitButtonClick(ActionEvent event)
        +void centerWindowOnScreen(Stage stage)
        #void onSignupButtonClick(ActionEvent event)
        }

        class NetworkController {}
    }
    'connections
    }

package Server {
    class SnakeServer {}
    class Database {}
    class MessageHandler {}
    class BroadcastMessageHandler{}
    'connections
    SnakeServer <--> Database
}

'connections
@enduml