@startuml
'https://plantuml.com/class-diagram
'- Indicates private
'+ Indicates public
'# Indicates protected

package Client {
    package Main {
        class Snake {}
    }
    package Model {
        class Snake {}
        class Player{
        -playerID
        -name
        -password
        +void addPlayer()
        }
        class Highscore{
        -playerID
        -highscore
        -datetime
        +void updateHighscore()
        }
        class Game{}
    }

    package View {
        class scoreView{}
        class registryView{}
        class loginView{}
        class arenaView{}
        class mainView{}
    }

    package Controller {
        class ScoreController {}
        class DatabaseController {
        -checkPlayer
        -addPlayer
        +Connection connector()
        }
        class ArenaController {
        +void onExitMenuClick(ActionEvent event)
        +void onGameInfoMenuClick(ActionEvent event)
        +void centerWindowOnScreen(Stage stage)
        }
        class MainController {}
        class ServerController{}
        class LoginController {
        +void initialize(URL location, ResourceBundle resources)
        #void onPlayButtonClick(ActionEvent event)
        -void run()
        -void drawBackground(GraphicsContext graphicsContext)
        -void onExitButtonClick(ActionEvent event)
        +void centerWindowOnScreen(Stage stage)
        #void onSignupButtonClick(ActionEvent event)
        }
    }
    'connections
    registryView --> Player
    loginView --> Player
    Highscore <-- scoreView
    Snake <-- loginView
    scoreView <-- scoreController
    registryView <-- databaseController
    loginView <-- databaseController
    arenaView <-- arenaController
    mainView <-- mainController
    ArenaController --> Snake
    ScoreController --> Highscore
    }

package Server {
    class SnakeServer
    class Database {}
    'connections
    SnakeServer <--> Database
}

'connections
ServerController <--> SnakeServer :network
DatabaseController <--> SnakeServer :network
@enduml