@startuml
'https://plantuml.com/class-diagram
'- Indicates private
'+ Indicates public
'# Indicates protected

package Client {
    package Main {
        class Snake {}
    }

    package Model {
        class Player{
        -playerID
        -name
        -password
        +void addPlayer()
        }

        class Highscore{
        -playerID
        -highscore
        -datetime
        +void updateHighscore()
        }
    }

    package View {
        class scoreView{}

        class registryView{}

        class loginView{}

        class arenaView{}
    }

    package Controller {
        class ScoreController {}

        class DatabaseServerController {
        -checkPlayer
        -addPlayer
        +Connection connector()
        }

        class ArenaController {
        +void onExitMenuClick(ActionEvent event)
        +void onGameInfoMenuClick(ActionEvent event)
        +void centerWindowOnScreen(Stage stage)
        }

        class LoginController {
        +void initialize(URL location, ResourceBundle resources)
        #void onPlayButtonClick(ActionEvent event)
        -void run()
        -void drawBackground(GraphicsContext graphicsContext)
        -void onExitButtonClick(ActionEvent event)
        +void centerWindowOnScreen(Stage stage)
        #void onSignupButtonClick(ActionEvent event)
        }
    }
    'connections
    registryView --> Player
    loginView --> Player
    Highscore <-- scoreView
    Snake <-- loginView
    scoreView <-- ScoreController
    registryView <-- DatabaseServerController
    loginView <-- DatabaseServerController
    arenaView <-- ArenaController
    ArenaController --> Snake
    ScoreController --> Highscore
    LoginController --> loginView
    arenaView --> Player
    arenaView --> Highscore
    }

package Server {
    class SnakeServer
    class Database {}
    'connections
    SnakeServer <--> Database
}

'connections
DatabaseServerController <--> SnakeServer :network
@enduml