@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant Client [
    =Client
    ----
    ""Socket""
    ]
participant Server [
        =Server
        ----
        ""Socket""
        ]

== Login ==
autonumber 10 "<font color=red><b>message "
Client -> Server: Login Request: {"sql_login_user": name}
Client <-- Server: Login Response: {"sql_login_user": name, sql_login_user_pass": pass}
== User Registration ==
autonumber 20 "<font color=red><b>message "
Client -> Server: User Registration Request: {"sql_register_user": name, "sql_register_pass": pass}
Client <-- Server: User Registration Response: {"sql_register_user_answer": "true"}
== Set Highscore ==
autonumber 30 "<font color=red><b>message "
Client -> Server: Set Highscore Request: {"sql_highscore_player": p, "sql_highscore_points": points}
Client <-- Server: Set Highscore Response: {"sql_highscore_answer": "true"}
== Get Highscore Table ==
autonumber 40 "<font color=red><b>message "
Client -> Server: Get Highscore Table Request JSON: {"sql_get_highscore_table": "true"}
Client <-- Server: Get Highscore Table Response: {"sql_get_highscore_table_answer": tableArray}

== Player Status ==
autonumber 50 "<font color=red><b>message "
Client -> Server: "Player 1" Status : {"Player": name, "Points": points, "Eatfruit": eatFruit, "Gameover": gameOver, "SnakeX": snakeX, "SnakeY": snakeY}
note left
optional for future
multi-client multiplayer feature
end note
Client -> Server: "Player 2" Status : {"Player": name, "Points": points, "Eatfruit": eatFruit, "Gameover": gameOver, "SnakeX": snakeX, "SnakeY": snakeY}
note over Client, Server: All messages are JSON Strings
@enduml