@startuml
'https://plantuml.com/class-diagram

package Client {
    package Main {
        class Snake {}
    }
    package Model {
        class Snake {}
        class Player{
        -playerID
        -name
        -password
        }
        class Highscore{
        -playerID
        -highscore
        -datetime
        }
        class Game{}
    }

    package View {
        class scoreView{}
        class registryView{}
        class loginView{}
        class arenaView{}
        class mainView{}
    }

    package Controller {
        class ScoreController {}
        class DatabaseController {
        -checkPlayer
        -addPlayer
        }
        class ArenaController {}
        class MainController {}
        class ServerController{}
    }
    'connections
    registryView --> Player
    loginView --> Player
    Highscore <-- scoreView
    Snake <-- loginView
    scoreView <-- scoreController
    registryView <-- databaseController
    loginView <-- databaseController
    arenaView <-- arenaController
    mainView <-- mainController
    ArenaController --> Snake
    ScoreController --> Highscore
    }

package Server {
    class SnakeServer
    class Database {}
    'connections
    SnakeServer <--> Database
}

'connections
ServerController <--> SnakeServer :network
DatabaseController <--> SnakeServer :network
@enduml